[package]
edition = "2024"
name = "test_esp"
rust-version = "1.88"
version = "0.1.0"

[[bin]]
name = "test_esp"
path = "./src/bin/main.rs"
test = false
bench = false
doctest = false

[dependencies]
keyboard_protocol = { path = "../keyboard_protocol" }

esp-hal = { version = "1.1.1", features = ["esp32s3", "unstable"] }
esp-alloc = "0.10.0"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }
esp-rtos = { version = "0.3.0", features = ["embassy", "esp32s3"] }
# esp-println = { version = "0.17.0", features = ["esp32s3"] }
esp-sync = { version = "0.2.1", features = ["esp32s3"] }

critical-section = "1.2.0"

synth = { path = "../synth" }
calc = { path = "../calc" }
micromath = "2.1.0"

bumpalo = "3.20.3"
rpds = { version = "1.2.1", default-features = false }
archery = "1.2.2"


# embedded-gui = { git = "https://github.com/ostev/embedded-gui.git", version = "0.0.23" }
embedded-gui = { path = "../../../embedded-gui" }

static_cell = "2.1.1"
usbd-hid = "0.10.0"
embassy-executor = "0.10.0"
embassy-time = "0.5.1"
embassy-sync = "0.8.0"
bytemuck = { version = "1.25.0", features = ["derive", "min_const_generics"] }
postcard = { version = "1.1.3", features = ["heapless"] }
embedded-hal = "1.0.0"
embedded-graphics = "0.8.2"
enumflags2 = { version = "0.7.12", features = ["serde"] }
heapless = { version = "0.9.3", features = ["serde"] }
u8g2-fonts = "0.8.0"
sequential-storage = "7.2.0"
serde = { version = "1.0.228", features = [
    "derive",
    "alloc",
], default-features = false }
circular-buffer = { version = "1.2.0", default-features = false }
embedded-storage-async = "0.4.1"
esp-storage = { version = "0.9.0", features = ["esp32s3"] }
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
esp-backtrace = { version = "0.19.0", features = [
    "println",
    "panic-handler",
    "esp32s3",
] }
embedded-hal-async = "1.0.0"
embedded-io-async = "0.7.0"
embassy-futures = "0.1.2"
esp-println = { version = "0.17.0", features = [
    "esp32s3",
    "uart",
], default-features = false }
libm = "0.2.16"
usb-device = { version = "0.3.2", features = ["control-buffer-256"] }
usbd-audio = "0.4.0"
atomic = { version = "0.6.1", default-features = false }
embedded-text = "0.7.3"


[patch.crates-io]
# embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy.git" }
# embassy-time-driver = { git = "https://github.com/embassy-rs/embassy.git" }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
